/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.startwithjava.Calculator;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;



public class CalculatorTest {
    private Calculator calculator;
    @BeforeEach
    public void setUp(){
        calculator = new Calculator();
    }
    @DisplayName("Test Divide method behavior when divisor is greater than zero")
    @Test public void testDivide_WhenDivisorIsGreaterThanZero_ReturnResult() {
        assertEquals(6, calculator.divide(12,2));
    }
    @DisplayName("Test Divide method behavior when divisor is zero")
    @Test public void testDivide_WhenDivisorIsZero_ThrowException() {
        assertThrows(ArithmeticException.class,()-> calculator.divide(2,0));
    }
}
